volumes:
  dbdata:

services:
  cranlogs:
    build:
      context: .
    ports:
      - "3000:80"
    command: nodemon bin/www.js
    volumes:
      - .:/src
    environment:
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_PASSWORD=secret

  postgres:
    image: "postgres:16.2-bookworm"
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql
      - ./db/1-proc.sql:/docker-entrypoint-initdb.d/1-proc.sql
      - ./db/2-create.sql:/docker-entrypoint-initdb.d/2-create.sql
      - ./db/3-data.sql:/docker-entrypoint-initdb.d/3-data.sql
      - ./sampledata:/sampledata
